### ISSUE TITLE
Doesn't work with Que (and version seems to be far behind in general)

### ISSUE THREAD

**Issue by D-side** [ankane/activejob_backport#4]
I tried to use this backport with Rails 4.1.6 and Que.

ActiveJob reports the enqueued job, but Que doesn't get to execute it, unless `Que.mode` is set to `:sync`, which doesn't make much sense for background job processor (except for testing jobs).

A search uncovered two relevant pull requests into ActiveJob itself:
- rails/rails#17223 that adds support for empty queue names
  - Que performs only jobs with empty queue name [?], out-of-the-box when ActiveJob passes in `'default'` as queue name.
  - When monkeypatched into the app, makes things work as expected
- rails/rails#19498 that makes ActiveJob not use named queues with Que integration at all
  - by @chanks, author of Que, and this PR reflects future changes to Que

I haven't looked much at the internals of this. Since this gem is not actively maintained now, I'll stick to Que itself as more reliable. Yet you could announce the state of the project in the `Readme`. It can be deduced from last commit date, sure, but it's not obvious :)

Shall I prepare a PR for these specific changes, or you can backport a more recent version of official ActiveJob with these changes already inside?

**Comment by ankane** [comment]
Hey @D-side, no plans to make any major updates, as this becomes more obsolete each day.
